GitHub-workflow.json
on: push
name: c1-pipeline
jobs:
  test:
    needs:
      - build
    runs-on: ubuntu-20.04
    steps:
      uses: actions/checkout@latest #v2
      #run: XXdotnet build;XX
      run: dotnet test 
        -p:CollectCovereage=true 
        -p CoverletOutputFormat=opencover 
        -p: CoverletOutput='test_coverage/'
        -l trx; # -l --logger=

  analyse:
    needs:
      - build
      - test
    runs-on: ubuntu-@v20.04
    env: # = "environment"
      SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
    steps:
      uses: actions/checkout@v2
      run: dotnet tool install 
        -g dotnet sonarscanner;
      run: dotnet sonarscanner begin 
        -k:'pizzabox' 
        -o:'TeamAlamo.NET' 
        -d:sonar.login:'$SONAR_TOKEN' 
      run: dotnet build
      run: dotnet sonarscanner end 
        -d:sonar.login:'$SONAR_TOKEN';

    package:
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
      needs:
        - analyze
      runs on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - run: docker image build -f Dockerfile -t pizzabox . ;
        #- run: docker image pizzabox fredbellotte/pizzabox;
        #- run: docker image pizzabox matthewttheroux/pizzabox;
        - run: docker image tag pizzabox matthewttheroux/pizzabox;

        # *pipes* the prompt to the console.stdin
        - run: echo @DOCKER_TOKEN  | docker login -v $DOCKER_USER --password-stdin;
        - run: docker push matthewttheroux/pizzabox;
        - run: docker logout

      #deploy to Azure app services
      deploy:
        needs: 
          - package
        runs-on: ubuntu-20.04
        steps:
          - uses: azure/login@v1
          - uses: azure/webapps-deploy@v2
            with:
              creds: ${{secrets.AZURE_CREDENTIALS}}
              app-name: pizzabox_matthewttheroux
              images: matthewttheroux/pizzabox

      